---
- name: Importando tarefas e configuracoes para "{{ ansible_distribution }}" vers√£o "{{ ansible_distribution_major_version }}"
  include_tasks: config2{{ ansible_distribution }}.yml
  
#- name: Instalando o PostgreSQL no CentOS
#  import_tasks: base-centos.yml
#  when: (ansible_distribution == "CentOS")
#
#- name: Instalando o PostgreSQL no RedHat
#  import_tasks: base-redhat.yml
#  when: (ansible_distribution == "RedHat")
#
#- name: Instalando o PostgreSQL no Debian
#  import_tasks: base-debian.yml 
#  when: (ansible_distribution == "Debian")
...
